version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1.0

defaults: &defaults
  docker:
    - image: cimg/node:12.22
  working_directory: ~/graphlib

commands:
  checkout_and_merge:
    steps:
      - checkout
      - run:
          name: Checkout master
          command: git checkout origin/master
      - run:
          name: Merge test branch
          command: |
            git config user.name "CircleCI"
            git config user.email "noop"
            git merge --no-edit "$CIRCLE_BRANCH"
      - attach_workspace:
          at: ~/graphlib

jobs:
  build:
    <<: *defaults
    environment:
      NODE_ENV: develop # Required because base image sets it to 'production'
    steps:
      - checkout_and_merge
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Run linting tasks
          command: npm run lint
      - run:
          name: Run tests
          command: npm t

  release:
    <<: *defaults
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout_and_merge
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@17

workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master
      - build:
          name: Build
      - release:
          name: Release
          context: nodejs-lib-release
          requires:
            - Build
          filters:
            branches:
              only:
                - master
