name: Build Status

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-firefox@latest

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        sudo apt-get install graphviz xvfb

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        KARMA_OPTS="--browsers Firefox,PhantomJS" xvfb-run --auto-servernum make -e test
